### ISSUE TITLE
elmenv-install: line 205: runhaskell: command not found

### ISSUE THREAD

**Issue by bstro** [sonnym/elmenv#10]
Just installed elmenv and attempting to install an older version of Elm. Upon typing `elmenv install 0.16.0`, I receive the error `~/.elmenv/libexec/elmenv-install: line 205: runhaskell: command not found`

**Comment by doppioslash** [comment]
Have you got `ghc` and `cabal` on the `PATH`?
If yes, what version are they?
And what operating system are you using?

**Comment by bstro** [comment]
Ah, didn't notice the final sentence in the `README`. I have `stack` installed but no ghc/cabal on my path. I guess i'll figure out how to do that. thx!
