### ISSUE TITLE
elmenv: no such command `--definitions'

### ISSUE THREAD

**Issue by nandin-borjigin** [sonnym/elmenv#11]
executing `elmenv install -l` returns `no such command '--definitions'`

**Comment by mrmurphy** [comment]
I'm encountering the same thing.

**Comment by sonnym** [comment]
My apologies for the long delay, but I finally got around to fixing this:  https://github.com/sonnym/elmenv/commit/8c0087db663d80524ecb5ea7eeaba92c617c038c
